#ifndef _EYEDEA_ERROR_TYPE_H_
#define _EYEDEA_ERROR_TYPE_H_

#define EYEDEA_SUCCESS			( 0)

#define EYEDEA_ERROR_INVALID_MEMORY	(-103)
#define EYEDEA_ERROR_SOCKET_CONNECT		(-100)
#define EYEDEA_ERROR_SOCKET_READ		(-101)
#define EYEDEA_ERROR_SOCKET_WRITE		(-102)
#define EYEDEA_ERROR_ALREADY_CONNECT    (-104)
#endif // #ifndef _EYEDEA_ERROR_TYPE_H_
